Fatal error: exception Failure("Attempted to call continue without being in a loop")
